"""One-time initialization: read system OpenCode config and create .env."""

import json
from pathlib import Path

AUTH_PATH = Path("~/.local/share/opencode/auth.json").expanduser()
ENV_PATH = Path(".env")
DEFAULT_MODEL = "opencode-go/deepseek-v4-flash"


def main():
    if not AUTH_PATH.exists():
        print(f"Error: auth.json not found at {AUTH_PATH}")
        print("Run 'opencode auth login' first.")
        return 1

    with open(AUTH_PATH) as f:
        auth = json.load(f)

    api_key = None
    for provider_id, creds in auth.items():
        if "opencode" in provider_id.lower() and creds.get("type") == "api":
            api_key = creds.get("key")
            break

    if not api_key:
        for creds in auth.values():
            if creds.get("type") == "api" and creds.get("key"):
                api_key = creds["key"]
                break

    if not api_key:
        print("Error: No API key found in auth.json")
        return 1

    content = (
        f"# Auto-generated by init_env.py\n"
        f"OPENCODE_API_KEY={api_key}\n"
        f"OPENCODE_DEFAULT_MODEL={DEFAULT_MODEL}\n"
    )
    ENV_PATH.write_text(content)
    print(f"Written to {ENV_PATH}")
    print(f"  API key: {api_key[:8]}...{api_key[-4:]}")
    print(f"  Default model: {DEFAULT_MODEL}")
    return 0


if __name__ == "__main__":
    exit(main())
